### ISSUE TITLE
Binary fails with missing libtinfo.so.6

### ISSUE THREAD

**Issue by arendsee** [coot/zephyr#61]
Downloading the binary for zephyr 0.3.2 fails on my Arch Linux system with the following error.

```
/zephyr: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```

I worked around this issue by simply symlinking my `libtinfo.so.5` library to `libtinfo.so.6`.

```
sudo ln -s /usr/lib/libtinfo.so.6 usr/liblibtinfo.so.5
```

I don't know if this work-around will go belly-up later (I haven't tested it), but I thought I'd pass it along in case it is helpful.

**Comment by toastal** [comment]
Maintaining libraries is a thankless job, but do you, @coot, think we could see a version bump? Just update the dependencies that are easy to, and rebuild with the latest glibc and libtinfo (5 -> 6) on latest Ubuntu?

**Comment by toastal** [comment]
I'm currently using `patchelf` to fake 6 as 5, because I'm in an environment with less control.

**Comment by coot** [comment]
@toastal maybe we need to add `apt update && apt upgrade` to the release workflow.

**Comment by toastal** [comment]
Wouldn't you need some system tracking if the linked libraries changed with new versions of Ubuntu every now and then? Ideally the dependency could be dropped like whatever was done in [purescript #4069](https://github.com/purescript/purescript/pull/4069) with `haskelline` if possible

```console
$ ldd (which zephyr)
	linux-vdso.so.1 (0x00007ffc051b0000)
	libm.so.6 => /nix/store/ikl21vjfq900ccbqg1xasp83kadw6q8y-glibc-2.32-46/lib/libm.so.6 (0x00007f6721eb4000)
	libz.so.1 => /nix/store/bl1kc9hw119ly7if07m2pbqak2yhars8-zlib-1.2.11/lib/libz.so.1 (0x00007f6721e97000)
	libtinfo.so.5 => /nix/store/77xh2kn0ywyh4cskvfnzw38xz4hqvxz1-ncurses-6.2-abi5-compat/lib/libtinfo.so.5 (0x00007f6721e31000)
	libpthread.so.0 => /nix/store/ikl21vjfq900ccbqg1xasp83kadw6q8y-glibc-2.32-46/lib/libpthread.so.0 (0x00007f6721e10000)
	librt.so.1 => /nix/store/ikl21vjfq900ccbqg1xasp83kadw6q8y-glibc-2.32-46/lib/librt.so.1 (0x00007f6721e05000)
	libutil.so.1 => /nix/store/ikl21vjfq900ccbqg1xasp83kadw6q8y-glibc-2.32-46/lib/libutil.so.1 (0x00007f6721dfe000)
	libdl.so.2 => /nix/store/ikl21vjfq900ccbqg1xasp83kadw6q8y-glibc-2.32-46/lib/libdl.so.2 (0x00007f6721df9000)
	libgmp.so.10 => /nix/store/v07f9gbkizyfcz98ssyhbq5jr6x823lm-gmp-6.2.1/lib/libgmp.so.10 (0x00007f6721d57000)
	libc.so.6 => /nix/store/ikl21vjfq900ccbqg1xasp83kadw6q8y-glibc-2.32-46/lib/libc.so.6 (0x00007f6721b96000)
	/nix/store/ikl21vjfq900ccbqg1xasp83kadw6q8y-glibc-2.32-46/lib/ld-linux-x86-64.so.2 => /nix/store/ikl21vjfq900ccbqg1xasp83kadw6q8y-glibc-2.32-46/lib64/ld-linux-x86-64.so.2 (0x00007f6721ff9000)
```

I believe this is usually more the package maintainer's burden consuming (e.g. not @coot 's problem), but most are probably just downloading the binary from GitHub because setting up Haskell is a burden. That said, perhaps it's a good time to bump dependencies after a while and re-release a new minor version. Hopefully, this doesn't need to happen too often.

Thanks a lot for the tool though. I couldn't have pitched PureScript _without_ cutting the bundle size in half with `zehpyr`.

**Comment by coot** [comment]
It is fixed with: https://github.com/coot/zephyr/releases/tag/refs%2Fheads%2Fmaster

**Comment by toastal** [comment]
awesome! Thanks a lot dude.
